// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI9XTYS_3GhNiFxxV0E0NxkZI9BCoysF4',
    appId: '1:419486302125:web:27c0ab8068faa0ff902b24',
    messagingSenderId: '419486302125',
    projectId: 'chat-app-5876d',
    authDomain: 'chat-app-5876d.firebaseapp.com',
    storageBucket: 'chat-app-5876d.appspot.com',
    measurementId: 'G-LDWV875GCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFKevTyK4H0prkIPNGNfset5hUjYOPKaA',
    appId: '1:419486302125:android:3827ad3db72571ce902b24',
    messagingSenderId: '419486302125',
    projectId: 'chat-app-5876d',
    storageBucket: 'chat-app-5876d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Dm_VU6A8k3A9oDyAt4gSwSGTcqRT9cc',
    appId: '1:419486302125:ios:3bf5596f0129f2d7902b24',
    messagingSenderId: '419486302125',
    projectId: 'chat-app-5876d',
    storageBucket: 'chat-app-5876d.appspot.com',
    iosClientId: '419486302125-t4rp9a556a8ujn33baspmkq96o1v7np4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Dm_VU6A8k3A9oDyAt4gSwSGTcqRT9cc',
    appId: '1:419486302125:ios:3bf5596f0129f2d7902b24',
    messagingSenderId: '419486302125',
    projectId: 'chat-app-5876d',
    storageBucket: 'chat-app-5876d.appspot.com',
    iosClientId: '419486302125-t4rp9a556a8ujn33baspmkq96o1v7np4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
