// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp5_UcsvemGiBiHjRVfEAWx6nMlblJ3Qg',
    appId: '1:718776154252:web:cf0526e5ab11f0601123a9',
    messagingSenderId: '718776154252',
    projectId: 'chat-app-e79bd',
    authDomain: 'chat-app-e79bd.firebaseapp.com',
    storageBucket: 'chat-app-e79bd.appspot.com',
    measurementId: 'G-R7HPYNBGTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgjpkoyG2ds5RXzXbY-TsczdmkrEQMMxI',
    appId: '1:718776154252:android:7aacdf0acef2c6471123a9',
    messagingSenderId: '718776154252',
    projectId: 'chat-app-e79bd',
    storageBucket: 'chat-app-e79bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACRHC4E3nRCA2SlWYzR1GUnRsS-TPnA24',
    appId: '1:718776154252:ios:863ea06b92b226b81123a9',
    messagingSenderId: '718776154252',
    projectId: 'chat-app-e79bd',
    storageBucket: 'chat-app-e79bd.appspot.com',
    iosClientId: '718776154252-jta8losf06h7pvpd280pv57skg8nfnob.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACRHC4E3nRCA2SlWYzR1GUnRsS-TPnA24',
    appId: '1:718776154252:ios:863ea06b92b226b81123a9',
    messagingSenderId: '718776154252',
    projectId: 'chat-app-e79bd',
    storageBucket: 'chat-app-e79bd.appspot.com',
    iosClientId: '718776154252-jta8losf06h7pvpd280pv57skg8nfnob.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
